environment:
    BUILD_SUBMITTER: hottub
    site: dcli.lix.cx
image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
    - hut
sources:
    - https://github.com/lixquid/deno-dcli
tasks:
    # Note: Remove this once deno is in the main alpine repo
    - prereq: |
          sudo apk add deno --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community
    - build: |
          cd *
          deno run -A build.ts
    - package: |
          cd */dist
          tar czvf ../dist.tgz *
          hut pages publish -d $site ../dist.tgz
